data_dir: ~/.local/share/assistant/meeting
collection: meeting
journal_data_dir: ~/.local/share/assistant/journal
person_data_dir: ~/.local/share/assistant/person
exclude:
  - .meetings-index.md
user_name: User
